export const COUNTRY_CODES = {
    'Australia': 'AU',
    'Brazil': 'BR',
    'Canada': 'CA',
    'Switzerland': 'CH',
    'Germany': 'DE',
    'Denmark': 'DK',
    'Spain': 'ES',
    'Finland': 'FI',
    'France': 'FR',
    'United Kingdom': 'GB',
    'Ireland': 'IE',
    'India': 'IN',
    'Iran': 'IR',
    'Mexico': 'MX',
    'Netherlands': 'NL',
    'Norway': 'NO',
    'New Zealand': 'NZ',
    'Serbia': 'RS',
    'Turkey': 'TR',
    'Ukraine': 'UA',
    'United States': 'US'
};