export interface IPQualityResult {
  ip: string;
  ipType?: string;
  isp?: string;
  org?: string;
  asn?: string | number;
  as?: string | number;
  ASN?: string | number;
  country?: string;
  countryCode?: string;
  fraudScore?: number;
  fraud_score?: number;
  abuseScore?: number;
  abuse_confidence_score?: number;
  isVpn?: boolean;
  vpn?: boolean;
  isProxy?: boolean;
  proxy?: boolean;
  isTor?: boolean;
  tor?: boolean;
  isNative?: boolean;
  isDualIsp?: boolean;
  cf_asn_bot_pct?: number;
  cf_asn_human_pct?: number;
  cf_asn_likely_bot?: boolean;
  aiReasoning?: string;
  ai_reasoning?: string;
  timestamp: string;
  [key: string]: unknown;
}
